apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: pre-zookeeper-logging
spec:
  baselineType: "PreAction"
  actionType: "pre-logging"
  necessary:
    fileLogging: "bool"
    stdoutLogging: "bool"
  steps:
    - name: logging
      type: "KubectlEdit" # KubectlGet、KubectlEdit、KubectlExec、Exec、HTTP
      cue: |
        output: {
          spec: parameters.spec
        }
        parameters: {
          spec: {
            parameters: {
              pod: {
                env: [
                {{- if .Necessary.stdoutLogging }}
                  {
                    name: "aliyun_logs_middlewarestdout"
                    value: "stdout"
                  },
                  {
                    name: "aliyun_logs_middlewarestdout_tags"
                    value: "middleware_name={{ .Globe.Name }}"
                  },
                {{ end }}
                {{- if .Necessary.fileLogging }}
                  {
                    name: "aliyun_logs_middlewarelogstash"
                    value: "/data/filelogs/*.log"
                  },
                  {
                    name: "aliyun_logs_middlewarelogstash_tags"
                    value: "middleware_name={{ .Globe.Name }}"
                  },
                {{ end }}
                ]
              }
            }
          }
          resource: {
            apiversion: "middleware.cn/v1"
            kind: "Middleware"
            name: "{{ .Globe.Name }}"
            namespace: "{{ .Globe.Namespace }}"
          }
        }
