replicaCount: 1
kubectl:
  installCRDs: true
  tolerations:
    - effect: NoSchedule
      key: harm.cn/type
      value: active-active
    - effect: NoSchedule
      key: harm.cn/system
  imagePullSecrets:
    - name: registrysecret
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: system
                operator: In
                values:
                  - "true"
          weight: 100


tolerations:
  - effect: NoSchedule
    key: harm.cn/type
    value: active-active
  - effect: NoSchedule
    key: harm.cn/system

podAntiAffinityTopologKey: "topology.kubernetes.io/zone"
podAntiAffinity: "hard"

nodeAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
          - key: system
            operator: In
            values:
              - "true"
      weight: 100

imagePullSecrets:
  - name: registrysecret

