apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: pre-zookeeper-operator-tolerations
spec:
  baselineType: "PreAction"
  actionType: "tolerations"
  necessary:
    tolerations: "array"
  steps:
    - name: tolerations
      type: "KubectlEdit" # KubectlGet、KubectlEdit、KubectlExec、Exec、HTTP
      cue: |
        output: {
          spec: parameters.spec
        }
        parameters: {
          spec: {
            deployment: {
              spec: {
                template: {
                  spec: {
                    {{- with .Necessary.tolerations }}
                    tolerations: {{ toCue . }}
                    {{- end }}
                  }
                }
              }
            }
          }
          resource: {
            apiversion: "middleware.cn/v1"
            kind: "MiddlewareOperator"
            name: "{{ .Globe.Name }}"
            namespace: "{{ .Globe.Namespace }}"
          }
        }
