{
 "title": "zookeeper",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(zk_uptime{middleware=\"zookeeper\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(zk_uptime{middleware=\"zookeeper\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(zk_uptime{middleware=\"zookeeper\",service=\"$service\"}, pod)"
   },
   {
    "name": "pv",
    "label": "pv",
    "query": "query_result(kube_persistentvolumeclaim_info{namespace=\"$namespace\", persistentvolumeclaim=\"$pvc\"})"
   },
   {
    "name": "pvc",
    "label": "pvc",
    "query": "query_result(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\", pod=\"$pod\"})"
   }
  ]
 },
 "panels": [
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "zookeeper服务是否可用（0:不可用;1:可用）",
   "type": "graph",
   "description": "zookeeper服务是否可用（0:不可用;1:可用）",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage(%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\",endpoint!=\"\",container!=\"\"}[5m]) ) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$pod\",resource=\"cpu\"}) by (pod)  * 100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory Working Set Usage(%)",
   "type": "graph",
   "description": "The percentage of requested memory resources that are actually being used (memory working set bytes) by the MySQL Pod.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\",endpoint!=\"\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$pod\",resource=\"memory\"}) by (pod) * 100",
     "legendFormat": "Mem"
    }
   ]
  },
  {
   "title": "Volume Capacity Usage(%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "used_size_kb{pv=\"$pv\"}*100/total_size_kb{pv=\"$pv\"}",
     "legendFormat": "Volume Usage-Common"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[1m]))",
     "legendFormat": "Network Receive"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[1m]))",
     "legendFormat": "Network Transmit"
    }
   ]
  },
  {
   "title": "数据大小",
   "type": "graph",
   "description": "zk_approximate_data_size 数据大小",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_approximate_data_size{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "节点选举情况",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_outstanding_requests{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{instance}}:{{state}}"
    }
   ]
  },
  {
   "title": "节点数量",
   "type": "graph",
   "description": "zk_znode_count znodes的数量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_znode_count{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "watches的数量",
   "type": "graph",
   "description": "zk_watch_count watches的数量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_watch_count{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "临时节点数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_ephemerals_count{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "connect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "连接数",
   "type": "graph",
   "description": "zk_num_alive_connections",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_num_alive_connections{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "堆积请求数",
   "type": "graph",
   "description": "zk_outstanding_requests 排队请求的数量，当ZooKeeper超过了它的处理能力时，这个值会增大，建议设置报警阀值为10",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_outstanding_requests{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Package", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "接收到客户端请求的包数量",
   "type": "graph",
   "description": "zk_packets_received 接收到客户端请求的包数量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_packets_received{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "发送给客户端的包数量",
   "type": "graph",
   "description": "zk_packets_sent 发送给客户单的包数量，主要是响应和通知",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_packets_sent{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Delay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "最高延迟",
   "type": "graph",
   "description": "最高延迟",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_max_latency{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "最低延迟",
   "type": "graph",
   "description": "最低延迟",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_min_latency{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "平均延迟",
   "type": "graph",
   "description": "平均延迟",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zk_avg_latency{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "打开文件数量",
     "type": "graph",
     "description": "zk_open_file_descriptor_count 打开文件数量，当这个值大于允许值得85%时报警",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_open_file_descriptor_count{namespace=\"$namespace\", service=\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "阻塞的sync",
     "type": "graph",
     "description": "zk_num_alive_connections",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_pending_syncs{namespace=\"$namespace\", service=\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "最大允许打开的文件数",
     "type": "graph",
     "description": "zk_max_file_descriptor_count 最大允许打开的文件数，由ulimit控制",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_max_file_descriptor_count{namespace=\"$namespace\", service=\"$service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}