apiVersion: v1
stringData:
  endpoint: {{ .Release.Name }}-zookeeper-client.{{ .Release.Namespace }}.svc
  port: "2181"
kind: Secret
metadata:
  name: {{ .Release.Name }}-credential
  namespace: {{ .Release.Namespace }}
type: Opaque