{{- if  .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    app: {{ include "zookeeper.fullname" . }}
  name: {{ include "zookeeper.fullname" . }}
spec:
  endpoints:
    - interval: 30s
      port: tcp-metrics
      relabelings:
      - replacement: zookeeper
        targetLabel: middleware
      - sourceLabels: [service]
        replacement: {{ include "zookeeper.fullname" . }}
        targetLabel: service
      metricRelabelings:
      - sourceLabels: [__name__]
        replacement: zk_${1}
        targetLabel: __name__
  selector:
    matchLabels:
      app: {{ include "zookeeper.fullname" . }}
{{- end }}
