# Copyright 2025 OpenSaola Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: pre-zookeeper-affinity
spec:
  baselineType: "PreAction"
  actionType: "affinity"
  necessary:
    podAntiAffinityTopologKey: ""
    podAntiAffinity: ""
    nodeAffinity: ""
  steps:
    - name: affinity
      type: "KubectlEdit" # KubectlGet、KubectlEdit、KubectlExec、Exec、HTTP
      cue: |
        output: {
          spec: parameters.spec
        }
        parameters: {
          spec: {
            parameters: {
              pod: {
              {{- if eq (semverCompare ">= 1.19-0" .Capabilities.KubeVersion.Version) false }}                        
                affinity: {                        
                {{- if eq .Necessary.podAntiAffinity "hard"}}                        
                  podAntiAffinity: {                        
                    requiredDuringSchedulingIgnoredDuringExecution: [                        
                      {                        
                        labelSelector: {                        
                          matchExpressions: [                        
                            {                        
                              key: "app"                        
                              operator: "In"                        
                              values: ["{{ .Globe.Name }}"]                        
                            },                        
                          ]                        
                        }                        
                      },                        
                    ]                        
                  }                        
                {{- else if eq .Necessary.podAntiAffinity "soft"}}                        
                  podAntiAffinity: {                        
                    preferredDuringSchedulingIgnoredDuringExecution: [                        
                      {                        
                        weight: 100                        
                        podAffinityTerm: {                        
                          topologyKey: "{{ .Necessary.podAntiAffinityTopologKey }}"                        
                          labelSelector: {                        
                            matchExpressions: [                        
                              {                        
                                key: "app"                        
                                operator: "In"                        
                                values: ["{{ .Globe.Name }}"]                        
                              },                        
                            ]                        
                          }                        
                        }                        
                      },                        
                    ]                        
                  }                        
                {{- end}}                                            
                {{- if .Necessary.nodeAffinity }}                        
                  {{- with .Necessary.nodeAffinity }}                        
                  nodeAffinity: {{ toCue . }}                        
                  {{- end }}                        
                {{- end }}                        
                }                        
              {{- end }}                        
              {{- if eq (semverCompare ">= 1.19-0" .Capabilities.KubeVersion.Version) true }}                        
                topologySpreadConstraints: [                        
                {{- if ne .Necessary.podAntiAffinityTopologKey "kubernetes.io/hostname"}}                        
                  {                        
                    maxSkew: 1                        
                    topologyKey: "{{ .Necessary.podAntiAffinityTopologKey | default "" }}"                        
                    {{- if eq .Necessary.podAntiAffinity "hard"}}                        
                    whenUnsatisfiable: "DoNotSchedule"                        
                    {{- else if eq .Necessary.podAntiAffinity "soft"}}                        
                    whenUnsatisfiable: "ScheduleAnyway"                        
                    {{- end }}                        
                    labelSelector: {                        
                      matchLabels: {                        
                        "app": "{{ .Globe.Name }}"                        
                      }                        
                    }                        
                  },                        
                {{- end }}                        
                  {                        
                    maxSkew: 1                        
                    topologyKey: "kubernetes.io/hostname"                        
                    {{- if eq .Necessary.podAntiAffinity "hard"}}                        
                    whenUnsatisfiable: "DoNotSchedule"                        
                    {{- else if eq .Necessary.podAntiAffinity "soft"}}                        
                    whenUnsatisfiable: "ScheduleAnyway"                        
                    {{- end }}                        
                    labelSelector: {                        
                      matchLabels: {                        
                        "app": "{{ .Globe.Name }}"                        
                      }                        
                    }                        
                  },                        
                ]                        
                {{- if .Necessary.nodeAffinity }}                        
                affinity: {                        
                  {{- with .Necessary.nodeAffinity }}                        
                  nodeAffinity: {{ toCue . }}                        
                  {{- end }}                        
                }                        
                {{- end}}                        
              {{- end}}                        
              }
            }
          }
          resource: {
            apiversion: "middleware.cn/v1"
            kind: "Middleware"
            name: "{{ .Globe.Name }}"
            namespace: "{{ .Globe.Namespace }}"
          }
        }
