apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: pre-zookeeper-heimdallr-hdpool
spec:
  baselineType: "PreAction"
  actionType: "hdpool"
  necessary:
    networkCardList: []
    annotations: {}
  steps:
    - name: hdpool
      type: "KubectlEdit" # KubectlGet、KubectlEdit、KubectlExec、Exec、HTTP
      cue: |
        output: {
          spec: parameters.spec
        }
        parameters: {
          spec: {
            parameters: {
              {{- if .Necessary.annotation }}
                pod: {
                  {{- with .Necessary.annotations }}
                  annotations: {{ toCue . }}
                  {{- end }}
                }
              {{- end }}
            }
          }
          resource: {
            apiversion: "middleware.cn/v1"
            kind: "Middleware"
            name: "{{ .Globe.Name }}"
            namespace: "{{ .Globe.Namespace }}"
          }
        }
