apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: pre-zookeeper-active-active
spec:
  baselineType: "PreAction"
  actionType: "active-active"
  necessary: { }
  steps:
    - name: isActiveActive
      output:
        type: "string"
        expose: true
      cmd:
        command:
          - "kubectl"
          - "get"
          - "ns"
          - "{{ .Necessary.namespace }}"
          - "-o"
          - "jsonpath='{.metadata.labels}'"
          - "|"
          - "awk"
          - '''/availableDomain/ {found=1; exit} END {if (found) print "true"; else print ""}'''
    - name: activeActive
      type: "KubectlEdit" # KubectlGet、KubectlEdit、KubectlExec、Exec、HTTP
      cue: |
        output: {
          spec: parameters.spec
        }
        parameters: {
          spec: {
            {{- if eq .Step.isActiveActive.output "true" }}
            statefulsetComponent: {
              broker: {
                spec: {
                  template: {
                    spec: {
                      initContainers: [
                        {
                          env: [
                            {
                              name: "ActiveActive"
                              value: "true"
                            },
                          ]
                        },
                      ]
                      serviceAccountName: "{{ .Globe.Name }}-sa"
                    }
                  }
                }
              }
            }
            {{- end }}
          }
          resource: {
            apiversion: "middleware.cn/v1"
            kind: "Middleware"
            name: "{{ .Globe.Name }}"
            namespace: "{{ .Globe.Namespace }}"
          }
        }
