# Copyright 2025 OpenSaola Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: middleware.cn/v1
kind: MiddlewareActionBaseline
metadata:
  name: zookeeper-restart
  annotations:
    alias: "服务重启"
spec:
  baselineType: "OpsAction"
  actionType: "restart"
  necessary:
  steps:
    - name: restart
      cmd:
        command:
          - "kubectl"
          - "patch"
          - "ZookeeperCluster"
          - "{{ .Globe.MiddlewareName }}"
          - "-n"
          - "{{ .Globe.Namespace }}"
          - "--type=merge"
          - "-p"
          - '''{"metadata":{"annotations":{"middleware.maintenance.lock":"graceful-restart","middleware.maintenance.step":"0"}}}'''
