apiVersion: middleware.cn/v1
kind: MiddlewareBaseline
metadata:
  name: zookeeper-cluster
  annotations:
    baselineName: "集群版"
    description: "集群版基线,包含核心功能和必要依赖,适用于快速部署和基本应用场景,稳定可靠,易于扩展和维护."
spec:
  operatorBaseline:
    name: zookeeper-operator-standard
    gvkName: v1beta1
  necessary:
    repository: ""
    version: '{"type":"version","label":"版本","required":true,"default":"3.7.1"}'
    resource:
      zookeeper:
        replicas: '{"type":"int","label":"实例数","required":true,"description":"节点数量，建议至少2个以保证高可用","default":3,"pattern":"^[1-9]\\d*$","placeholder":"请输入实例数"}'
        volume:
          size: '{"type":"int","label":"存储大小","required":true,"description":"请输入存储大小","pattern":"^[1-9]\\d*$","placeholder":"请输入存储大小"}'
          storageClass: '{"type":"storageClass","label":"存储类","required":true,"description":"请选择存储","placeholder":"请选择存储"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"2"}'
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"请输入自定义配额,单位为Core","placeholder":"请输入自定义配额,单位为Core","default":"1"}'
          memory: '{"type":"string","label":"内存","required":true,"description":"请输入自定义配额,单位为Gi","placeholder":"请输入自定义配额,单位为Gi","default":"4"}'
  preActions:
    - name: pre-zookeeper-alertrule-labels
      parameters:
        labels: {}
      exposed: false
    - name: pre-zookeeper-logging
      parameters:
        fileLogging: true
        stdoutLogging: true
      exposed: true
    - name: pre-zookeeper-active-active
      parameters:
      exposed: false
    - name: pre-zookeeper-affinity
      parameters:
        podAntiAffinityTopologKey: "kubernetes.io/hostname"
        podAntiAffinity: "soft"
        nodeAffinity: {}
      exposed: true
    - name: pre-zookeeper-tolerations
      parameters:
        tolerations: []
      exposed: true
  parameters:
    replicas: "{{ .Necessary.resource.zookeeper.replicas }}"
    version: "{{ .Necessary.version }}"
    image:
      repository: "{{ .Necessary.repository }}/zookeeper"
      tag: "3.7.1-2"
      pullPolicy: IfNotPresent
    kubernetesClusterDomain: "cluster.local"
    pod:
      labels:
        middleware: zookeeper
      resources:
        requests:
          cpu: '"{{ .Necessary.resource.zookeeper.requests.cpu }}"'
          memory: '"{{ .Necessary.resource.zookeeper.requests.memory }}"'
        limits:
          cpu: '"{{ .Necessary.resource.zookeeper.limits.cpu }}"'
          memory: '"{{ .Necessary.resource.zookeeper.limits.memory }}"'
      env:
        - name: TZ
          value: Asia/Shanghai
      serviceAccountName: default
    config:
      skipACL: "yes"
      autoPurgeSnapRetainCount: 20
      autoPurgePurgeInterval: 48
    storageType: persistence
    persistence:
      reclaimPolicy: Retain
      spec:
        storageClassName: "{{ .Necessary.resource.zookeeper.volume.storageClass }}"
        resources:
          requests:
            storage: "{{ .Necessary.resource.zookeeper.volume.size }}"
  configurations:
    - name: zookeeper-connection-credential
      values: {}
    - name: zookeeper-servicemonitor
      values: {}
    - name: zookeeper-alertrule
      values: {}