apiVersion: middleware.cn/v1
kind: MiddlewareBaseline
metadata:
  name: zookeeper-cluster
  annotations:
    baselineName: "Cluster"
    description: "Cluster Mode Baseline, incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
spec:
  operatorBaseline:
    name: zookeeper-operator-standard
    gvkName: v1beta1
  necessary:
    repository: ""
    version: '{"type":"version","label":"Version","required":true,"default":"3.7.2"}'
    resource:
      zookeeper:
        replicas: '{"type":"int","label":"Replicas","required":true,"description":"Nodes,It is recommended to have at least 3 to ensure high availability.","default":3,"pattern":"^[3-9]$","placeholder":"Please enter the number of instances"}'
        volume:
          size: '{"type":"int","label":"StorageSize","required":true,"description":"Please enter the storage size","pattern":"^[1-9]\\d*$","placeholder":"Please enter the storage size"}'
          storageClass: '{"type":"storageClass","label":"StorageClass","required":true,"description":"Please select storage","placeholder":"Please select storage"}'
        requests:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"1"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"2"}'
        limits:
          cpu: '{"type":"string","label":"CPU","required":true,"description":"Please enter a custom quota, the unit is `Core`","placeholder":"Please enter a custom quota, the unit is `Core`","default":"1"}'
          memory: '{"type":"string","label":"Memory","required":true,"description":"Please enter a custom quota, the unit is `Gi`","placeholder":"Please enter a custom quota, the unit is `Gi`","default":"4"}'
  preActions:
    - name: pre-zookeeper-heimdallr-hdpool
      parameters:
        networkCardList: [ ]
        annotations: { }
      fixed: false
      exposed: true
    - name: pre-zookeeper-alertrule-labels
      parameters:
        labels: {}
      exposed: false
    - name: pre-zookeeper-logging
      parameters:
        fileLogging: true
        stdoutLogging: true
      exposed: true
    - name: pre-zookeeper-active-active
      parameters:
      exposed: false
    - name: pre-zookeeper-affinity
      parameters:
        podAntiAffinityTopologKey: "kubernetes.io/hostname"
        podAntiAffinity: "soft"
        nodeAffinity: {}
      exposed: true
    - name: pre-zookeeper-tolerations
      parameters:
        tolerations: []
      exposed: true
  parameters:
    sasl:
      user: super
      password: Hc@Cloud01
#    acl:
#      superUser: super
#      superPassword: Hc@Cloud01
    replicas: "{{ .Necessary.resource.zookeeper.replicas }}"
    version: "{{ .Necessary.version }}"
    image:
      repository: "{{ .Necessary.repository }}/zookeeper"
      tag: '{{ if eq .Necessary.version "3.7.1" }}3.7.1-2{{ else if eq .Necessary.version "3.7.2" }}3.7.2-zk{{ end }}'
      pullPolicy: IfNotPresent
    kubernetesClusterDomain: "cluster.local"
    pod:
      labels:
        middleware: zookeeper
      resources:
        requests:
          cpu: '"{{ .Necessary.resource.zookeeper.requests.cpu }}"'
          memory: '"{{ .Necessary.resource.zookeeper.requests.memory }}"'
        limits:
          cpu: '"{{ .Necessary.resource.zookeeper.limits.cpu }}"'
          memory: '"{{ .Necessary.resource.zookeeper.limits.memory }}"'
      env:
        - name: TZ
          value: Asia/Shanghai
      serviceAccountName: default
    config:
      skipACL: "yes"
      autoPurgeSnapRetainCount: 20
      autoPurgePurgeInterval: 48
    storageType: persistence
    persistence:
      reclaimPolicy: Retain
      spec:
        storageClassName: "{{ .Necessary.resource.zookeeper.volume.storageClass }}"
        resources:
          requests:
            storage: "{{ .Necessary.resource.zookeeper.volume.size }}"
  configurations:
    - name: zookeeper-connection-credential
      values: {}
    - name: zookeeper-servicemonitor
      values: {}
    - name: zookeeper-alertrule
      values: {}
