apiVersion: middleware.cn/v1
kind: MiddlewareOperatorBaseline
metadata:
  name: zookeeper-operator-highly-available
  annotations:
    baselineName: "HighAvailability"
    description: "High Availability/HA Baseline,incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
spec:
  gvks:
    - name: v1beta1
      group: "zookeeper.pravega.io"
      version: "v1beta1"
      kind: "ZookeeperCluster"
  globe:
    repository: "10.10.101.172:443"
    project: "middleware"
    # resource:
    #   limits:
    #     cpu: "200m"
    #     memory: "512Mi"
    #   requests:
    #     cpu: "100m"
    #     memory: "256Mi"
  preActions:
    - name: pre-zookeeper-operator-affinity
      parameters:
        podAntiAffinityTopologKey: "kubernetes.io/hostname"
        podAntiAffinity: "soft"
        nodeAffinity: {}
      exposed: true
    - name: pre-zookeeper-operator-tolerations
      parameters:
        tolerations: []
      exposed: true
  permissionScope: "Cluster"
  permissions:
    - serviceAccountName: "{{ .Globe.Name }}-zookeeper-operator"
      rules:
        - apiGroups:
            - zookeeper.pravega.io
          resources:
            - "*"
          verbs:
            - "*"
        - apiGroups:
            - ""
          resources:
            - pods
            - pods/exec
            - services
            - endpoints
            - persistentvolumeclaims
            - events
            - configmaps
            - secrets
            - serviceaccounts
          verbs:
            - "*"
        - apiGroups:
            - apps
          resources:
            - deployments
            - daemonsets
            - replicasets
            - statefulsets
          verbs:
            - "*"
        - apiGroups:
            - policy
          resources:
            - poddisruptionbudgets
          verbs:
            - "*"
  deployment:
    spec:
      replicas: 3
      selector:
        matchLabels:
          name: "{{ .Globe.Name }}"
      template:
        metadata:
          labels:
            name: "{{ .Globe.Name }}"
            component: zookeeper-operator
        spec:
          serviceAccountName: "{{ .Globe.Name }}-zookeeper-operator"
          containers:
            - name: "{{ .Globe.Name }}"
              image: '{{ if ne .Globe.repository "" }}{{ .Globe.repository }}/{{ end }}{{ .Globe.project }}/zookeeper-operator:v1.3.0'
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 6000
                  name: metrics
              command:
                - zookeeper-operator
              env:
                - name: WATCH_NAMESPACE
                  value: ""
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: "{{ .Globe.Name }}"
              resources:
                limits:
                  cpu: 200m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
          imagePullSecrets:
            - name: registrysecret
  configurations:
    - name: "crd-zookeepercluster"
      values: {}
    - name: "zookeeper-operator-dashboard"
      values: {}
