# Copyright 2025 OpenSaola Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: middleware.cn/v1
kind: MiddlewareOperatorBaseline
metadata:
  name: zookeeper-operator-standard
  annotations:
    baselineName: "Standard"
    description: "Standard Baseline,incorporating core functionality and essential dependencies, is tailored for rapid deployment and fundamental application scenarios. It delivers stable and reliable performance, and is designed for ease of extension and maintenance."
spec:
  gvks:
    - name: v1beta1
      group: "zookeeper.pravega.io"
      version: "v1beta1"
      kind: "ZookeeperCluster"
  globe:
    repository: "10.10.101.172:443"
    project: "middleware"
    # resource:
    #   limits:
    #     cpu: "200m"
    #     memory: "512Mi"
    #   requests:
    #     cpu: "100m"
    #     memory: "256Mi"
  preActions:
    - name: pre-zookeeper-operator-affinity
      parameters:
        podAntiAffinityTopologKey: "kubernetes.io/hostname"
        podAntiAffinity: "soft"
        nodeAffinity: {}
      exposed: true
    - name: pre-zookeeper-operator-tolerations
      parameters:
        tolerations: []
      exposed: true
  permissionScope: "Cluster"
  permissions:
    - serviceAccountName: "{{ .Globe.Name }}-zookeeper-operator"
      rules:
        - apiGroups:
            - zookeeper.pravega.io
          resources:
            - "*"
          verbs:
            - "*"
        - apiGroups:
            - ""
          resources:
            - pods
            - pods/exec
            - services
            - endpoints
            - persistentvolumeclaims
            - events
            - configmaps
            - secrets
            - serviceaccounts
          verbs:
            - "*"
        - apiGroups:
            - apps
          resources:
            - deployments
            - daemonsets
            - replicasets
            - statefulsets
          verbs:
            - "*"
        - apiGroups:
            - policy
          resources:
            - poddisruptionbudgets
          verbs:
            - "*"
  deployment:
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: "{{ .Globe.Name }}"
      template:
        metadata:
          labels:
            name: "{{ .Globe.Name }}"
            component: zookeeper-operator
        spec:
          serviceAccountName: "{{ .Globe.Name }}-zookeeper-operator"
          containers:
            - name: "{{ .Globe.Name }}"
              image: '{{ if ne .Globe.repository "" }}{{ .Globe.repository }}/{{ end }}{{ .Globe.project }}/zookeeper-operator:v1.3.0'
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 6000
                  name: metrics
              command:
                - zookeeper-operator
              env:
                - name: WATCH_NAMESPACE
                  value: ""
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: "{{ .Globe.Name }}"
              resources:
                limits:
                  cpu: 200m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
          imagePullSecrets:
            - name: registrysecret
  configurations:
    - name: "crd-zookeepercluster"
      values: {}
    - name: "zookeeper-operator-dashboard"
      values: {}
