apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: zookeeper-connection-credential
spec:
  template: |
    apiVersion: v1
    stringData:
      endpoint: {{ .Globe.Name }}-zookeeper-client.{{ .Globe.Namespace }}.svc
      port: "2181"
    kind: Secret
    metadata:
      name: {{ .Globe.Name }}-credential
      namespace: {{ .Globe.Namespace }}
    type: Opaque